version: "3.8"

services:
  macdentry:
    build:
      dockerfile: workerDev.dockerfile
    command: entry_macd.py david
    depends_on:
      - mariadb
      - dbworker
    volumes:
      - .:/var/www/html
      - logs:/var/www/html/logs
  tslexit:
    build:
      dockerfile: workerDev.dockerfile
    restart: always
    command: exit-tsl.py david
    depends_on:
      - mariadb
      - dbworker
    volumes:
      - .:/var/www/html
      - logs:/var/www/html/logs
volumes:
  logs: