version: "3.8"

services:
  macdentry:
    build:
      dockerfile: workerDev
    command: code/entry-macd.py david
    depends_on:
      - mariadb
      - dbworker
    volumes:
      - code:/var/www/html
  tslexit:
    build:
      dockerfile: workerDev
    restart: always
    command: code/exit-tsl.py david
    depends_on:
      - mariadb
      - dbworker
    volumes:
      - code:/var/www/html
volumes:
  dbData:
  grafanaConf:
  code: