version: "3.8"

services:
  mariadb:
    build:
      dockerfile: mariaImage
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: binance
      MYSQL_USER: binance
      MYSQL_PASSWORD: binance
    volumes:
      - dbDataDEV:/var/lib/mysql
  adminer:
    image: adminer
    #restart: always
    ports:
      - 8070:8080
    depends_on: 
      - mariadb
  testdataframe:
    build:
      dockerfile: worker.dockerfile
    command: testDeploy.py test
    depends_on:
      - mariadb
volumes:
  dbDataDEV: