version: "3.8"

services:
  mariadb:
    build:
      dockerfile: mariaImage
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: binance
      MYSQL_USER: binance
      MYSQL_PASSWORD: binance
    volumes:
      - dbData:/var/lib/mysql
  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: ae3e-plotly-panel
    ports:
      - 3000:3000
    volumes:
      - grafanaConf:/var/lib/grafana
    depends_on: 
      - mariadb
  adminer:
    image: adminer
    #restart: always
    ports:
      - 8080:8080
    depends_on: 
      - mariadb
  dbworker:
    image: worker:0.0.2
    #build:
      #dockerfile: worker
    command: code/sistema.py david dbWorker
    depends_on:
      - mariadb
  dbminer:
    image: worker:0.0.2
    #build:
      #dockerfile: worker    
    command: code/sistema.py david dbMiner
    depends_on:
      - mariadb
      - dbworker
#  dbcalculator:
#    build: 
#      dockerfile: worker
#    command: code/sistema.py david dbCalculator
#    depends_on: 
#      - mariadb
#      - dbworker
volumes:
  grafanaConf:
  dbData: