version: "3.8"

services:
  mariadb:
    build:
      dockerfile: mariaImage.dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: binance
      MYSQL_USER: binance
      MYSQL_PASSWORD: binance
    volumes:
      - dbData:/var/lib/mysql
  prometheus_sql:
    image: prom/mysqld-exporter
    ports:
      - 9104:9104
    depends_on:
      - mariadb
    environment:
      DATA_SOURCE_NAME: binance:binance@(mariadb:3306)/binance
  prometheus:
    build:
      dockerfile: prometheusImage.dockerfile
    ports:
      - 9090:9090
    depends_on:
      - mariadb
      #- prometheusagent
  #es01:
      #image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
      #container_name: es01
      #environment:
        #discovery.type: "single-node"
      #ulimits:
        #memlock:
          #soft: -1
          #hard: -1
      #volumes:
        #- dataES:/usr/share/elasticsearch/data
      #ports:
        #- 9200:9200
volumes:
  dbData:
  dataES: