version: "3.8"

services:
  mariadb:
    build:
      dockerfile: mariaImage.dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: binance
      MYSQL_USER: binance
      MYSQL_PASSWORD: binance
    volumes:
      - dbData:/var/lib/mysql
volumes:
  dbData: