version: "3.8"

services:
  mariadb:
    build:
      dockerfile: mariaImage
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: binance
      MYSQL_USER: binance
      MYSQL_PASSWORD: binance
    volumes:
      - dbDataDEV:/var/lib/mysql
  adminer:
    image: adminer
    #restart: always
    ports:
      - 8000:8080
    depends_on: 
      - mariadb
  dbworker:
    build:
      dockerfile: worker.dockerfile
    command: sistema.py david dbWorker
    depends_on:
      - mariadb
  #dbminer:
    #build:
      #dockerfile: worker.dockerfile
    #command: sistema.py david dbMiner
    #depends_on:
      #- mariadb
  #dbcalculator:
    #build: 
      #dockerfile: worker.dockerfile
    #command: sistema.py david dbCalculator
    #depends_on: 
      #- mariadb
volumes:
  dbDataDEV: