version: "3.8"

services:
  mariadb:
    build:
      dockerfile: mariaImage
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: binance
      MYSQL_USER: binance
      MYSQL_PASSWORD: binance
    volumes:
      - dbDataDEV:/var/lib/mysql
  prometheusagent:
    image: prom/mysqld-exporter
    ports:
      - 9104:9104
    depends_on:
      - mariadb
    environment:
      DATA_SOURCE_NAME: binance:binance@(mariadb:3306)/binance
  prometheus:
    build:
      dockerfile: prometheusImage.dockerfile
    ports:
      - 9090:9090
    depends_on:
      - mariadb
      - prometheusagent
  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: ae3e-plotly-panel
    ports:
      - 3080:3000
    volumes:
      - grafanaConfDEV:/var/lib/grafana
    depends_on: 
      - mariadb
  adminer:
    image: adminer
    #restart: always
    ports:
      - 8000:8080
    depends_on: 
      - mariadb
  dbworker:
    build:
      dockerfile: worker.dockerfile
    command: sistema.py david dbWorker
    depends_on:
      - mariadb
  dbminer:
    build:
      dockerfile: worker.dockerfile
    command: sistema.py david dbMiner
    depends_on:
      - mariadb
      - dbworker
  dbcalculator:
    build: 
      dockerfile: worker.dockerfile
    command: sistema.py david dbCalculator
    depends_on: 
      - mariadb
      - dbworker
volumes:
  dbDataDEV:
  grafanaConfDEV: