version: "3.8"

services:
  symbolupdater:
    build:
      dockerfile: workerDev.dockerfile
    command: worker-symbolUpdater.py david
    depends_on:
      - mariadb
    volumes:
      - .:/var/www/html
      - logs:/var/www/html/logs
  dataminer:
    build:
      dockerfile: workerDev.dockerfile
    command: worker-miner.py david
    depends_on:
      - mariadb
      - dbworker
    volumes:
      - .:/var/www/html
      - logs:/var/www/html/logs
volumes:
  logs: